[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx prisma migrate deploy && node dist/main'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
